server:
  port: 6001
#授权码模式下防止同一主机 cookie冲突，否则报错如下
#Possible CSRF detected - state parameter was required but no state could be found
  servlet:
    session:
      cookie:
        name: TOURNESOL-BLOG
logging:
  level:
    org.springframework.security: debug
    com.tournesol.core: debug
    com.tournesol.common: debug
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

  servlet:
    multipart:
      max-file-size: 70MB
      max-request-size: 100MB
  application:
    name: service-blog
  profiles:
    include: d
  datasource:
    url: jdbc:mysql://8.142.135.239:3306/huiren-cloud-bd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: huiren@123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 8.142.135.239
    port: 6388
    password: huiren@2022$
    jedis:
      pool:
        max-active: 300
        max-wait: -1ms
        max-idle: 20
        min-idle: 0
    timeout: 1000ms
mybatis-plus:
  global-config:
    worker-id: 1
    datacenter-id: 1
    db-config:
      id-type: id_worker
  mapper-locations: classpath*:mapper/*.xml






