server:
  port: 6001
#授权码模式下防止同一主机 cookie冲突，否则报错如下
#Possible CSRF detected - state parameter was required but no state could be found
  servlet:
    session:
      cookie:
        name: TOURNESOL-CORE
logging:
  level:
    org.springframework.security: debug
    com.tournesol.core: debug
    com.tournesol.common: debug
spring:
  servlet:
    multipart:
      max-file-size: 70MB
      max-request-size: 100MB
  application:
    name: service-core
  profiles:
    include: d
  datasource:
    url: jdbc:mysql://39.107.13.44:3306/huiren-cloud-core?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: bibilili4455
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 39.98.45.114
    port: 6388
    password: huiren@123
    jedis:
      pool:
        max-active: 300
        max-wait: -1ms
        max-idle: 20
        min-idle: 0
    timeout: 1000ms
security:
  oauth2:
    resource:
      jwt:
        key-value: huiren.com
mybatis-plus:
  global-config:
    worker-id: 1
    datacenter-id: 1
    db-config:
      id-type: id_worker
  mapper-locations: classpath*:mapper/*.xml
#  百度云配置
baidu:
  appId: 26973518
  apiKey: 8Rsgy2gSxz9btPzs7bvLWE2V
  secretKey: P3nTKpEzgle5wrs90PmCyCndb6WPkwRn
baiduSpeech:
  appId: 26164205
  apiKey: niaZhKVOjhdVqw6BxYNApDbS
  secretKey: o85ELVoE809Ig4kwRP7POjGLWLujRLK5





