spring:
  cloud:
    inetutils:
      preferredNetworks: //匹配正则表达式优先使用ip段，list配置 从上到下找，找到哪个用哪个
        - 10.2.0
    nacos:
      discovery:
        username: nacos
        password: nacos
      server-addr: http://101.43.152.143:8848
      namespace: public
knife4j:
  enable: true
  basic:
    enable: true
    username: admin
    password: 123456
feign:
  client:
    config:
      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
        loggerLevel: FULL #  日志级别
